name: 'make for qygame-docker'
autho: wcq
description: 'make for qygame-docker'

inputs:
  qygame_token:
    description: 'Set a generated GITHUB_TOKEN for pushing to the remote branch.'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'