name: make

on:
  push:
    tags:
      - '**'
      - '!docker-compose**'
      - '!qyaction**'
      - '!k8s**'
  
jobs:
  build: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 #all history for all branches and tags
      - uses: ./
        with:
          qygame_token: ${{ secrets.QYGAME_ACTION }}