name: make

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        include:
          ##fix linux/xxx invalid reference format
          - platform: linux/amd64
            suffix: linux-amd64
            runs_on: ubuntu-latest
          - platform: linux/arm64
            suffix: linux-arm64
            runs_on: ubuntu-24.04-arm
    ##避免 linux/arm64 在 amd64 runner 上跑慢
    runs-on: ${{ matrix.runs_on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image for ${{ matrix.platform }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          ##缓存加速
          cache-from: type=gha,scope=qy-compiler-${{ matrix.suffix }}
          cache-to: type=gha,mode=max,scope=qy-compiler-${{ matrix.suffix }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/qy-compiler:${{ github.ref_name }}-${{ matrix.suffix }}
          secrets: |
            ##Dockerfile中调用其他github仓库, 只能使用GIT_AUTH_TOKEN
            GIT_AUTH_TOKEN=${{ secrets.QYGAME_ACTION }}

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-platform manifest
        run: |
          docker buildx imagetools create -t ghcr.io/${{ github.repository_owner }}/qy-compiler:latest \
            -t ghcr.io/${{ github.repository_owner }}/qy-compiler:${{ github.ref_name }} \
            ghcr.io/${{ github.repository_owner }}/qy-compiler:${{ github.ref_name }}-linux-amd64 \
            ghcr.io/${{ github.repository_owner }}/qy-compiler:${{ github.ref_name }}-linux-arm64
