name: make

on:
  push:
    tags:
      - '*'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: clay2019/qy_dev:latest
          secrets: |
            ##Dockerfile中调用其他github仓库, 只能使用GIT_AUTH_TOKEN
            GIT_AUTH_TOKEN=${{ secrets.QYGAME_ACTION }}
