name: make

on:
  push:
    tags:
      - '*'

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/qy-compiler:latest
            ghcr.io/${{ github.repository_owner }}/qy-compiler:${{ github.ref_name }}
          secrets: |
            ##Dockerfile中调用其他github仓库, 只能使用GIT_AUTH_TOKEN
            GIT_AUTH_TOKEN=${{ secrets.QYGAME_ACTION }}
